### ISSUE TITLE
Error when installing suctionnetAPI by pip install .

### ISSUE THREAD

**Issue by Gaurav37** [graspnet/suctionnetAPI#2]
Defaulting to user installation because normal site-packages is not writeable
Processing /home/gaurav/suctionnetAPI
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/gaurav/.local/lib/python3.6/site-packages (from suctionnetAPI==1.0.0) (1.19.5)
Requirement already satisfied: scipy in /home/gaurav/.local/lib/python3.6/site-packages (from suctionnetAPI==1.0.0) (1.5.4)
Collecting transforms3d==0.3.1
  Using cached transforms3d-0.3.1.tar.gz (62 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: open3d>=0.8.0.0 in /home/gaurav/.local/lib/python3.6/site-packages (from suctionnetAPI==1.0.0) (0.14.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from suctionnetAPI==1.0.0) (4.62.3)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (from suctionnetAPI==1.0.0) (4.5.5.62)
Requirement already satisfied: trimesh in /usr/local/lib/python3.6/dist-packages (from suctionnetAPI==1.0.0) (3.9.40)
Collecting suction_nms
  Using cached suction_nms-1.0.0.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rsgs6en3/suction-nms_7193e40d909142c294d1bb903759e78f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rsgs6en3/suction-nms_7193e40d909142c294d1bb903759e78f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cc8h3lf9
       cwd: /tmp/pip-install-rsgs6en3/suction-nms_7193e40d909142c294d1bb903759e78f/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rsgs6en3/suction-nms_7193e40d909142c294d1bb903759e78f/setup.py", line 15, in <module>
      ext_modules=cythonize("suction_nms.pyx"),
    File "/home/gaurav/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 973, in cythonize
      aliases=aliases)
    File "/home/gaurav/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/home/gaurav/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'suction_nms.pyx' doesn't match any files
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/37/9d/290ba120ab22f13e7348b1436706e2e2df7886dcd948cee654f5b573e088/suction_nms-1.0.0.tar.gz#sha256=031e9d93aeb6eab170979af5edde87ece4c400ca988731da1fe5d645d99a500f (from https://pypi.org/simple/suction-nms/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement suction_nms (from suctionnetapi) (from versions: 1.0.0)
ERROR: No matching distribution found for suction_nms

**Comment by Gaurav37** [comment]
I installed suction-nms by sequentially following below commands.
```
git clone https://github.com/intrepidChw/suctionnms.git
cd suctionnms
pip install .
```
