### ISSUE TITLE
安装时出现Cython错误

### ISSUE THREAD

**Issue by hawkeex** [graspnet/suctionnetAPI#4]
`Collecting suction_nms (from suctionnetAPI==1.0.0)
  Using cached suction_nms-1.0.0.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9eu4mcn4/suction-nms_e4b8ecf8ee7e4cf780c0045254916bf5/setup.py", line 15, in <module>
          ext_modules=cythonize("suction_nms.pyx"),
        File "/home/eggsy/anaconda3/envs/py3-mink/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/home/eggsy/anaconda3/envs/py3-mink/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/home/eggsy/anaconda3/envs/py3-mink/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'suction_nms.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`
即使从源下载suction_nms后install .也会出现同样的错误

**Comment by hawkeex** [comment]
https://github.com/intrepidChw/suctionnms, 将setup.py中的suction_nms改为suction-nms可解决
